-- ============================================================
-- ⚠️ ARCHIVO OBSOLETO — NO EJECUTAR (las políticas fallaban)
-- ============================================================
-- La tabla `orders` YA fue creada exitosamente (CREATE TABLE IF
-- NOT EXISTS sí es válido en Postgres). Lo que falló fueron las
-- políticas al final, porque usaban "CREATE POLICY IF NOT EXISTS"
-- (sintaxis inválida en PostgreSQL — solo CREATE TABLE/INDEX la
-- soportan). Por eso truncaba con:
--   ERROR: 42601: syntax error at or near "NOT"
--
-- Las políticas de RLS para `orders` ya están incluidas (con la
-- sintaxis correcta) en: database/fix_rls_policies_v3.sql
-- Ejecuta ese archivo, no este.
-- ============================================================
