-- ============================================================
-- ⚠️ ARCHIVO OBSOLETO — NO EJECUTAR
-- ============================================================
-- Este archivo tenía un error de sintaxis: PostgreSQL no soporta
-- "CREATE POLICY IF NOT EXISTS" (esa sintaxis solo existe para
-- CREATE TABLE / CREATE INDEX). Por eso fallaba con:
--   ERROR: 42601: syntax error at or near "NOT"
--
-- Usa en su lugar: database/fix_rls_policies_v3.sql
-- (incluye todo lo de aquí, con la sintaxis correcta y es
-- seguro de re-ejecutar cuantas veces quieras)
-- ============================================================
